[package]
name = "wasm-for-rage"
version = "0.1.0"
edition = "2021"
authors = ["ghosty2004"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.64"
wasm-bindgen = "0.2.87"
